cookie: 
  data_ticket=cO3Jj13v94MnYYGko+zxt8Gjh/F0OcjBb82fTUhtS6qsowVtEUpTI+y0VSkUGxZb; 
  slave_sid=b3NrTFNiN3ZQekU0SzdQdVNDTno0OG0yUVh0UF93Q0RPUzM0RmtPaUJTaWtGVzFad3FudVpJUXo3X3JXdGprZmQ0NUZhSU5ITEdyVHJTdXlLcVhtbUdaZGpvd3NPT3hIMWJ6Tk1TSGVxRjI0QUgxQXRpNFI1blFpMUVWMVloQktmOEFvR2dMSkNhaXd0ZHpD; 
  slave_user=gh_b05c590577c4; 
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36..."
token: 2088180987

count: 20

# db: mysql://username:password@localhost/dbname
db: mysql+pymysql://we-rss:123456@119.3.239.67/we-rss